name: Test workflow
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        run: actions/checkout@v3
      - name: Print message
        run: echo "Hello world"
