name: Test workflow
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Print message
        run: echo "Hello world"
      - name: Check nodejs version
        run: node -v
